- codeOfConduct.md
> docs: add codeOfConduct.md

- .gitignore
- README.md
> docs: update readme and .gitignore

- README.md
> docs: add nice message

- .travis.yml
> chore: included heroku api_key

- script/seed.js
- server/api/users.spec.js
- server/db/models/user.js
- server/db/models/user.spec.js
> chore: basic user model addressing issue #14

- server/db/models/wine.js
> chore: add wine model

- package-lock.json
- package.json
- server/db/models/orders.js
> add orders model # 16

- seed.js
- server/db/models/cartItem.js
> chore: add wine seed data

- script/seed.js
> fix: rename imageURL in seed

- server/api/index.js
- server/api/wines.js
- server/api/wines.spec.js
- server/db/models/wine.js
> feat: serve router all wines incl test

- client/components/index.js
- client/components/winesIcon.js
- client/components/winesIcon.spec.js
- client/components/winesList.js
- client/components/winesList.spec.js
- client/routes.js
- client/store/allWines.js
- client/store/index.js
- public/style.css
> feat: All wines view

- server/api/wines.js
- server/api/wines.spec.js
> feat: get single wine by id route and test

- client/components/user-home.js
- client/store/user.js
- client/store/user.spec.js
- server/auth/auth.spec.js
- server/auth/google.js
- server/db/models/user.js
> login and oauth

- server/api/cart.js
- server/api/cart.spec.js
- server/api/index.js
- server/api/orders.js
- server/api/orders.spec.js
> Backend routers for orders

- client/components/SingleWine/SingleWineContainer.js
- client/components/navbar.js
- client/routes.js
- package-lock.json
- package.json
- public/index.html
- public/nprogress.css
---
Added NProgress animation that is invoked on 'Add To Cart' button
> style: added NProgress bar to add-to-cart button

- server/auth/auth.spec.js
- server/auth/index.js
> Signup cart

- client/components/SingleWine/SingleWineContainer.js
- client/store/cart.js
- client/store/cart.spec.js
> refactor: changed action creator to thunk

- client/store/allWines.spec.js
- client/store/cart.js
- client/store/user.js
- server/api/index.js
> login cart add and security update

- client/store/cart.js
- client/store/index.js
---
Implement localStorage to persist cart after refresh.  No other parts of redux store are persisted for security reasons.
> feat: localStorage hooked up to persist cart

- server/db/models/wine.spec.js
> test: added wine model  specs

- client/components/user-home.js
- client/components/user-home.spec.js
- client/store/user.js
---
Fixed fetchCart issues - should make Rhianna's life easier!
> 81 hit database and fetch cart on google login

- client/components/CartIcon.js
- client/components/CartIcon.spec.js
- client/components/WineList/winesList.spec.js
- client/components/navbar.js
- public/index.html
- public/style.css
---
Added test for CartIcon component.
> 76 add mini cart to navbar

- client/components/Stripe/CheckoutForm.js
- server/api/cart.js
- server/index.js
--secures the total so that the logic is done in the route so the actual charge is not easily hacked (though some bulky logic still repeated for "total" display)
--updates logged-in checkout route to make sure another cart is opened in database for that user
--also fixed bug: post-checkout "getOrder()" to "getCart()"
> security update: checkout form

- client/components/Stripe/AddressForm.js
- client/components/Stripe/CheckoutForm.js
- client/store/address.js
- client/store/index.js
- server/db/models/orders.js
- server/index.js
--changed order model to accommodate name and address/billing address (only recording shipping atm)
--added reducer for pulling address info from the address form
** there will be some overlap with my other pull request so whichever is pulled first I will probably rework the other **
> closed orders record name, address, total

- server/index.js
> fix: user var in /charge route

- client/components/navbar.js
- client/components/user-home.js
- client/routes.js
- client/store/index.js
- client/store/user.js
- server/api/cart.js
- server/auth/google.js
- server/index.js
I broke this up into two commits, please take a look at them individually.
- in the first one I realized when you refresh a logged in user, their cart will double in size. so I made sure localStorage was only keeping track of the guest user's cart, and when a person logs in, the localStorage cart is cleared
- then in order to still be able to see a cart in the refresh, I let the UserHome component fetch the cart from the backend as well
> Only save guest cart

- client/components/Cart/Cart.js
- client/components/auth-form.js
> Style login #90

- client/components/OrderRow.js
- client/components/UserMenu/OrderDetails.js
> separate order row component

- script/seed.js
---
Added 8 more wines to seed file.
> added more bottles to seed file

- client/components/Cart/Cart.js
- client/components/Stripe/ThankYou.js
- client/components/navbar.js
- public/style.css
> Thank you image fix

- client/components/Cart/Cart.js
- client/store/cart.js
- client/store/cart.spec.js
- server/api/cart.js
--corrects icon amount update
--deletes order item from cart props
--bug: order items are not being saved in db for logged-in users
> Icon fix: updates quantity correctly

- client/components/Cart/CartRow.js
> aligns with columns

- client/components/Cart/Cart.js
> fix: change handler for new style in-cart update

- client/components/UserMenu/EmptyOrderHistory.js
- client/components/UserMenu/OrderHistory.js
> fix: empty order history shows up if there are no closed orders

- client/components/Cart/Cart.js
- client/components/Cart/CartRow.js
- public/style.css
> fix: cart row wine name centering and MUI selector

- client/store/cart.js
- client/store/cart.spec.js
- client/store/index.js
> Commented out consolelog redux logger

- client/components/SingleWine/SingleWine.js
- public/style.css
---
Minor adjustment to margins and global font-size.
> Font sizing

- client/components/Cart/CartRow.js
- server/api/cart.js
> fix: 0 available in cart update

- server/index.js
> security: stripe key secure: proceed with caution
